---
image:
  repository: consensys/istanbul-tools
  tag: 'latest'
  pullPolicy: Always

# the number of Validators you want
rawGenesisConfig:
  blockchain:
    nodes:
      count: 4

azure:
  # the script/bootstrap.sh uses the name 'default-pod-identity' so only change this if you altered the name
  identityName: default-pod-identity
  keyvaultName: azure-keyvault