---
image:
  repository: consensys/istanbul-tools
  tag: 'latest'
  pullPolicy: Always

# the values here are from the example config file found in the the [Quickstart](https://besu.hyperledger.org/en/latest/Tutorials/Create-IBFT-Network/)
rawGenesisConfig:
  genesis:
    config:
      chainId: 2018
      constantinoplefixblock: 0
      ibft2:
        blockperiodseconds: 2
        epochlength: 30000
        requesttimeoutseconds: 10
    nonce: '0x0'
    timestamp: '0x58ee40ba'
    gasLimit: '0x47b760'
    difficulty: '0x1'
    mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365'
    coinbase: '0x0000000000000000000000000000000000000000'
    # insert your prod accounts here
    alloc: {} 
  blockchain:
    nodes:
      generate: true
      count: 4

azure:
  # the script/bootstrap.sh uses the name 'default-pod-identity' so only change this if you altered the name
  identityName: default-pod-identity
  keyvaultName: azure-keyvault

